-- vim.g.dap_virtual_text = true
-- vim.opt.colorcolumn = "80"
--
-- -- Disable persistent undo
-- vim.opt.undofile = false
-- listchars=eol:↵,trail:~,tab:>-,nbsp:␣
-- vim.cmd(hi EoLSpace ctermbg=238 guibg=#333333)
-- vim.cmd(match EoLSpace /\s\+$/)
